# Generated by Django 5.1.4 on 2024-12-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsmodel",
            name="home_page",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentsmodel",
            name="response_to",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.commentsmodel",
            ),
        ),
    ]
