# Generated by Django 5.1.4 on 2024-12-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_commentsmodel_response_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsmodel",
            name="response_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="comments.commentsmodel",
            ),
        ),
    ]
