# Generated by Django 5.1.4 on 2024-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_alter_commentsmodel_response_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentsmodel",
            name="posted_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-12-12 12:00:00"
            ),
            preserve_default=False,
        ),
    ]
