# Generated by Django 5.1.4 on 2024-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=128)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("username", "email"), name="unique_username_email"
                    )
                ],
            },
        ),
    ]
