# Generated by Django 5.1.4 on 2024-12-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dummy_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("home_page", models.URLField(null=True)),
                (
                    "response_to",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comments.commentsmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dummy_user.dummyusermodel",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "response_to"), name="unique_id_response_to"
                    )
                ],
            },
        ),
    ]
