# Generated by Django 5.1.4 on 2024-12-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_commentsmodel_posted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentsmodel",
            options={"ordering": ("-posted_at",)},
        ),
    ]
